### ISSUE TITLE
1.3.0 breaks Rake task

### ISSUE THREAD

**Issue by threedaymonk** [damian/jshint#21]
7f9dbe6d removes the default value of `reporter_name`, which makes the supplied `jshint:lint` task blow up:

```
TypeError: no implicit conversion of nil into String
.../gems/jshint-1.3.0/lib/jshint/cli.rb:6:in `const_get'
.../gems/jshint-1.3.0/lib/jshint/cli.rb:6:in `run'
.../gems/jshint-1.3.0/lib/jshint/tasks/jshint.rake:12:in`block (2 levels) in <top (required)>'
Tasks: TOP => default => jshint:lint
```

**Comment by damian** [comment]
I just released v1.3.1 containing this fix along with the RSpec 3 upgrade.
